#!bash

[[ -n ${ZSH_VERSION-} ]] &&
  GIT_HUB_ROOT="$0" ||
  GIT_HUB_ROOT="$BASH_SOURCE"
[[ $GIT_HUB_ROOT =~ ^/ ]] ||
  GIT_HUB_ROOT="$PWD/$GIT_HUB_ROOT"
export GIT_HUB_ROOT="$(cd "$(dirname $GIT_HUB_ROOT)"; pwd)"

echo "Deprecated: 'source $GIT_HUB_ROOT/init'"
echo "Switch to:  'source $GIT_HUB_ROOT/.rc'"

source "$GIT_HUB_ROOT/.rc"
