#!/usr/bin/env bash

interactive() {
  [[ -n $GIT_HUB_TEST_INTERACTIVE ]] && return 0

  if [[ -t 0 && -t 1 ]]; then
    return 0
  else
    return 1
  fi
}

prompt() {
  echo "$prompt_msg"
  exit 0
}

read-config-value() {
  if [[ -n $GIT_HUB_TEST_MAKE ]]; then
    if [[ $1 == login ]]; then
      value=aocole
      return
    fi
    if [[ $1 == use-auth ]]; then
      value=
    fi
  fi
  value="$(git config -f $GIT_HUB_CONFIG "git-hub.$1")" || value="$2"
}
