#!/usr/bin/env bash

set -e

command:cache-clear() {
  a="$(prompt "Delete all of '$GIT_HUB_CACHE'? [yN]")"
  if [ "$a" == y ]; then
    rm -fr "$GIT_HUB_CACHE"
    msg_ok="'$GIT_HUB_CACHE' deleted."
  else
    msg_ok="'$GIT_HUB_CACHE' not deleted."
  fi
}
