#!/usr/bin/env bash

set -e

command:notify-list() {
  require-auth
  local all=false
  "$do_all" && all=true

  title="Notifications for '$login' (all=$all):"

  list_size=$Infinity
  interactive=false
  report-list \
    "/notifications?all=$all" \
    'subject/title reason updated_at unread subject/type subject/url'
}

format-entry:notify-list() {
  if "$raw_output"; then
    out "$2"
  else
    local url="${7/api\./}"
    url="${url/repos\//}"
    color-table-row \
      "%2d)" LABEL "$1" \
      "" "" "$2" \
      " (%s)" YELLOW "$3"
    color-table-row \
      "      %s)" DATE "${4%T*}" \
      "unread=%s" YELLOW "$5" \
      "(%s)" LABEL "$6" \
      "" "" "$url"
  fi
}
