#!/usr/bin/env bash

set -e

command:members() {
  require-auth
  get-args team_id
  if [[ ! "$team_id" =~ ^[0-9]+$ ]]; then
    git hub org-members "$team_id"
    return
  else
    git hub team-members "$team_id"
  fi
}

command:member-get() {
  require-auth
  get-args team_id user
  api-get "/teams/$team_id/members/$user"
  msg_ok="'$user' is of team (id) '$team_id'"
  msg_404="'$user' is NOT a member of team (id) '$team_id'"
}

command:member-add() {
  require-auth
  get-args team_id user
  api-put "/teams/$team_id/members/$user"
  msg_ok="'$user' is now on team (id) '$team_id'"
}

command:member-remove() {
  require-auth
  get-args team_id user
  api-delete "/teams/$team_id/members/$user"
  msg_ok="'$user' is no longer on team (id) '$team_id'"
}

# vim: set lisp:
