#!/usr/bin/env bash

set -e

command:keys() {
  get-args owner:get-user
  report-list \
    "/users/$owner/keys" \
    key
}

format-entry:keys() {
  if "$raw_output"; then
    out "$2"
  else
    say "Public SSH keys for '$owner':"
    printf "%d) %s\n" "$1" "$2"
  fi
}

command:keys-add() {
  require-auth
  get-args title key
  api-post /user/keys "$(json-dump-object title "$title" key "$key")"
  msg_ok="Public key successfully added."
}

# vim: set lisp:
