#!bash

[[ -n ${ZSH_VERSION-} ]] &&
  GIT_HUB_ROOT="$0" ||
  GIT_HUB_ROOT="$BASH_SOURCE"
if [[ "$GIT_HUB_ROOT" =~ ^/ ]]; then
  GIT_HUB_ROOT="$(dirname $GIT_HUB_ROOT)"
  GIT_HUB_ROOT="$(dirname $GIT_HUB_ROOT)"
  GIT_HUB_ROOT="$(dirname $GIT_HUB_ROOT)"
  export GIT_HUB_ROOT

  export PATH="$GIT_HUB_ROOT/lib:$PATH"
  export MANPATH="$GIT_HUB_ROOT/man:$MANPATH"

  # Completion facilities
  if [[ -n ${BASH_VERSION-} ]]; then
    # Bash
    if [ "$(type -t __gitcomp 2> /dev/null)" != function ]; then
      if [ -e /etc/bash_completion.d/git ]; then
	source /etc/bash_completion.d/git
      else
	source "$GIT_HUB_ROOT/lib/git-hub.d/git-completion"
      fi
    fi
    source "$GIT_HUB_ROOT/lib/git-hub.d/completion"
  elif [[ -n ${ZSH_VERSION-} ]]; then
    # Zsh
    #
    # Prepend to `fpath` the path of the directory containing our zsh
    # completion script, so that our completion script will be hooked into
    # the zsh completion system.
    fpath=($GIT_HUB_ROOT/share/zsh-completion $fpath)
  fi

else
  echo "source the absolute path of '$GIT_HUB_ROOT'"
fi
