#!/usr/bin/env bash

set -e

command:open() {
  get-args '?owner:get-user/repo:get-repo'

  get-browser

  "$browser" "http://github.com/$owner/$repo"
}

get-browser() {
  browser="$(get-hub-config browser)"
  [ -n "$browser" ] && return

  for browser in firefox chromium; do
    [ -n "$(type $browser)" ] && return
  done

  die <<...
Can't determine your web browser. Try something like:

    git hub config browser chromium

...
}

# vim: set lisp:
