#!/usr/bin/env bash

set -e

command:open() {
  set -- "${command_arguments[@]}"

  url="$(git hub url $@)"

  get-browser

  "$browser" "$url" &
  msg_ok="$browser $url"
}

get-browser() {
  browser="$(get-hub-config browser)"
  [ -n "$browser" ] && return

  for browser in firefox chromium-browser; do
    [ -n "$(type $browser)" ] && return
  done

  die <<...
Can't determine your web browser. Try something like:

    git hub config browser chromium

...
}

# vim: set lisp:
